// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package types

import (
	"fmt"

	"github.com/denkhaus/bitshares/util"
	"github.com/denkhaus/logging"
	"github.com/juju/errors"
)

type AccountBalanceID struct {
	ObjectID
}

func (p AccountBalanceID) Marshal(enc *util.TypeEncoder) error {
	if err := enc.EncodeUVarint(uint64(p.Instance())); err != nil {
		return errors.Annotate(err, "encode instance")
	}

	return nil
}

func (p *AccountBalanceID) Unmarshal(dec *util.TypeDecoder) error {
	var instance uint64
	if err := dec.DecodeUVarint(&instance); err != nil {
		return errors.Annotate(err, "decode instance")
	}

	p.number = UInt64((uint64(SpaceTypeProtocol) << 56) | (uint64(ObjectTypeAccountBalance) << 48) | instance)
	return nil
}

type AccountBalanceIDs []AccountBalanceID

func (p AccountBalanceIDs) Marshal(enc *util.TypeEncoder) error {
	if err := enc.EncodeUVarint(uint64(len(p))); err != nil {
		return errors.Annotate(err, "encode length")
	}

	for _, ex := range p {
		if err := enc.Encode(ex); err != nil {
			return errors.Annotate(err, "encode AccountBalanceID")
		}
	}

	return nil
}

func AccountBalanceIDFromObject(ob GrapheneObject) AccountBalanceID {
	id, ok := ob.(*AccountBalanceID)
	if ok {
		return *id
	}

	p := AccountBalanceID{}
	p.MustFromObject(ob)
	if p.ObjectType() != ObjectTypeAccountBalance {
		panic(fmt.Sprintf("invalid ObjectType: %q has no ObjectType 'ObjectTypeAccountBalance'", p.ID()))
	}

	return p
}

//NewAccountBalanceID creates an new AccountBalanceID object
func NewAccountBalanceID(id string) GrapheneObject {
	gid := new(AccountBalanceID)
	if err := gid.Parse(id); err != nil {
		logging.Errorf(
			"AccountBalanceID parser error %v",
			errors.Annotate(err, "Parse"),
		)
		return nil
	}

	if gid.ObjectType() != ObjectTypeAccountBalance {
		logging.Errorf(
			"AccountBalanceID parser error %s",
			fmt.Sprintf("%q has no ObjectType 'ObjectTypeAccountBalance'", id),
		)
		return nil
	}

	return gid
}
