// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package types

import (
	"fmt"

	"github.com/denkhaus/bitshares/util"
	"github.com/denkhaus/logging"
	"github.com/juju/errors"
)

type CommitteeMemberID struct {
	ObjectID
}

func (p CommitteeMemberID) Marshal(enc *util.TypeEncoder) error {
	if err := enc.EncodeUVarint(uint64(p.Instance())); err != nil {
		return errors.Annotate(err, "encode instance")
	}

	return nil
}

func (p *CommitteeMemberID) Unmarshal(dec *util.TypeDecoder) error {
	var instance uint64
	if err := dec.DecodeUVarint(&instance); err != nil {
		return errors.Annotate(err, "decode instance")
	}

	p.number = UInt64((uint64(SpaceTypeProtocol) << 56) | (uint64(ObjectTypeCommitteeMember) << 48) | instance)
	return nil
}

type CommitteeMemberIDs []CommitteeMemberID

func (p CommitteeMemberIDs) Marshal(enc *util.TypeEncoder) error {
	if err := enc.EncodeUVarint(uint64(len(p))); err != nil {
		return errors.Annotate(err, "encode length")
	}

	for _, ex := range p {
		if err := enc.Encode(ex); err != nil {
			return errors.Annotate(err, "encode CommitteeMemberID")
		}
	}

	return nil
}

func CommitteeMemberIDFromObject(ob GrapheneObject) CommitteeMemberID {
	id, ok := ob.(*CommitteeMemberID)
	if ok {
		return *id
	}

	p := CommitteeMemberID{}
	p.MustFromObject(ob)
	if p.ObjectType() != ObjectTypeCommitteeMember {
		panic(fmt.Sprintf("invalid ObjectType: %q has no ObjectType 'ObjectTypeCommitteeMember'", p.ID()))
	}

	return p
}

//NewCommitteeMemberID creates an new CommitteeMemberID object
func NewCommitteeMemberID(id string) GrapheneObject {
	gid := new(CommitteeMemberID)
	if err := gid.Parse(id); err != nil {
		logging.Errorf(
			"CommitteeMemberID parser error %v",
			errors.Annotate(err, "Parse"),
		)
		return nil
	}

	if gid.ObjectType() != ObjectTypeCommitteeMember {
		logging.Errorf(
			"CommitteeMemberID parser error %s",
			fmt.Sprintf("%q has no ObjectType 'ObjectTypeCommitteeMember'", id),
		)
		return nil
	}

	return gid
}
