// Code generated by "stringer -type=ObjectType"; DO NOT EDIT.

package types

import "strconv"

const (
	_ObjectType_name_0 = "ObjectTypeUndefined"
	_ObjectType_name_1 = "ObjectTypeBaseObjectTypeAccountObjectTypeAssetObjectTypeForceSettlementObjectTypeCommiteeMemberObjectTypeWitnessObjectTypeLimitOrderObjectTypeCallOrderObjectTypeCustomObjectTypeProposalObjectTypeOperationHistoryObjectTypeWithdrawPermissionObjectTypeVestingBalanceObjectTypeWorkerObjectTypeBalance"
)

var (
	_ObjectType_index_1 = [...]uint16{0, 14, 31, 46, 71, 95, 112, 132, 151, 167, 185, 211, 239, 263, 279, 296}
)

func (i ObjectType) String() string {
	switch {
	case i == -1:
		return _ObjectType_name_0
	case 1 <= i && i <= 15:
		i -= 1
		return _ObjectType_name_1[_ObjectType_index_1[i]:_ObjectType_index_1[i+1]]
	default:
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
